# Generated by Django 4.2.16 on 2025-04-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_bot_alter_operation_status_delete_botstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-created']},
        ),
    ]
