# Generated by Django 4.2.16 on 2025-04-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_signal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingsettings',
            name='telegram_bot_token',
        ),
        migrations.RemoveField(
            model_name='tradingsettings',
            name='telegram_chat_id',
        ),
    ]
