# Generated by Django 4.2.16 on 2025-05-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_remove_tradingsettings_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10),
        ),
        migrations.AlterField(
            model_name='signalgroup',
            name='direction',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10),
        ),
    ]
