# Generated by Django 4.2.16 on 2025-05-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_signal_signal_type_alter_signalgroup_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='api_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
